static/_redirects
Adding redirect for prisma.pan.dev
Allows for reaching prisma.pan.dev by navigating to either `pan.dev/prisma` or `developers.paloaltonetworks.com/prisma`
n/a
=> add prisma redirect

docusaurus.config.js
Current Prisma SD-WAN Legacy navigation link is outdated and results in a 404 (Page Not Found). Updated Prisma SASE SD-WAN Legacy nav link to `sdwan/api/legacy`.
Tested the following: 
- Navigation Menu: Developer Docs -> Secure Access Service Edge -> Prisma SD-WAN -> Prisma SD-WAN Legacy
- Product Group Card: Secure Access Service Edge -> Prisma SD-WAN -> Prisma SD-WAN Legacy
=> Fix Prisma SD-WAN Legacy nav link

src/css/custom.scss
Remove CSS style overriding default `CodeBlock` overflow behavior, where users are given the option to toggle line/word wrap if supported by language.
Some code snippets extend beyond visible area which resulted in ugly wrapping.
See deploy preview for full test. Tested locally.
https://user-images.githubusercontent.com/9343811/201747286-1f48bbf1-9241-46c4-acd5-49ee507119b1.mov
=> Remove code block word wrap CSS override

docusaurus.config.js
The SASE auth create token endpoint requires a CORS anywhere proxy in order to support requests from the browser.
Allow customers/users to generate tokens from the browser.
Tested using my own service account and TSG ID. Will follow up and test other endpoints to see if any more need the proxy.
=> Add CORS proxy to SASE auth API

src/theme/NavbarItem/DropdownNavbarItem.js
Currently, the `<DropdownNavbarItemMobile />` component does not properly handle conditional rendering of `product.docs` and `product.apiDocs`. Products that did not contain an `apiDocs` or `docs` property within `docusaurus.config.js` caused the site to crash when resizing the browser to mobile viewports.
This PR introduces the fix to the bug described above by conditionally mapping and rendering `product.apiDocs` and `product.docs` to prevent the site from crashing when viewing in mobile.
Tested locally with https://github.com/PaloAltoNetworks/pan.dev/pull/213
1. Navigate to https://pan-dev-f1b58--pr213-6jmh959f.web.app/
2. Decrease browser size to mobile
3. Observe page crash and error message `Cannot read properties of undefined (reading 'map')` …
=> [Bug] DropdownNavbarItemMobile: Cannot read properties of undefined (reading 'map')

src/css/custom.scss
This change leverages a nested `has()` selector to limit smooth scrolling to home page.
When navigating from one page to another, users may experience a momentary delay as the browser scrolls from the current position to the top of the page:
https://user-images.githubusercontent.com/9343811/213208175-199cb159-75cd-4647-9e71-f96cf3ce590c.mov
After change:
https://user-images.githubusercontent.com/9343811/213208769-a06818fd-3867-47a1-a993-b9e71d021042.mov
> Notice smooth scrolling is preserved for home page
Local dev server - see deploy preview for live demo
=> Limit smooth scrolling to homepage

src/components/Medium/index.js, src/components/ProductLandingPage/Hero/Hero.js, src/components/Slider/Slider.js
**Environment:** Dev 
**Device:** Mac | Chrome 
This PR introduces a fix for local console errors caused by React Slick Carousel. The console error was caused by a known issue when using custom arrows, more info can be found [here](https://github.com/akiran/react-slick/issues/623#issuecomment-629764816). In addition, the `Slider` component is now a single component that can be used across the app and can receive [custom props](https://react-slick.neostack.com/docs/api/) for customizability.
_**Note: While working on this issue, another [console error](https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi/54686484#54686484) (unrelated to Slick Carousel) came to my attention which will be addressed in a later PR.**_
There …
=> [Bug] Resolve local console errors caused by React Slick Carousel

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-live.yml, .github/workflows/deploy-preview.yml
* Update CodeQL to v2
* Update checkout to v3
* Remove firebase-tools step from deploy-preview workflow
* Configure `setup-node` step for deploy-preview and deploy-live to set node version to 18 and enable yarn caching
* Add build envar for error reporter to deploy-live
=> Upgrade and cleanup workflows

.yarnrc
The default yarn registry (https://registry.yarnpkg.com) has a TLS setup that is incompatible with SSL decryption. The following StackOverflow page suggests that the yarn registry is simply a proxy for https://registry.npmjs.org.
Source: https://stackoverflow.com/questions/58071109/difference-between-yarn-registry-and-npm-registry
This change uses `.yarnrc` to change the default registry URL to https://registry.npmjs.org to help avoid SSL decryption issues.
Improve DX for pan.dev contributors who work behind an SSL decryption proxy.
Output of `yarn config list` after updating `.yarnrc`:
```
yarn config v1.22.19
info yarn config
{
'version-tag-prefix': 'v',
'version-git-tag': true,
'version-commit-hooks': true,
'version-git-sign': false,
'version-git-message': 'v%s',
'init-version': …
```
=> Use .yarnrc to change default registry url

src/components/Slider/Slider.js, src/components/Slider/Slider.scss
This PR addresses the rendering of original Slick arrows within the carousel. These arrows should not appear, since we are using custom arrows instead.
Tested with both dark/light mode to ensure that the original arrows were not being rendered on top of the custom arrows and arrow functionality remains intact.
**Homepage**
**Terraform Landing Page**
**Homepage**
**Terraform Landing Page**
=> [Bug] Remove original Slick arrow styling

src/components/Medium/index.js
This PR introduces content sanitization for our Medium Blog Cards. Currently, there are unseen elements being rendered onto the DOM. Since the Blog Cards only show a preview of the blog content, it may be unnecessary to inject the html of the entire blog. The approach taken is to only render up to the first paragraph of each blog content and omitting all the other proceeding elements.
Inspected DOM for each blog card content to ensure there weren't any unseen elements being injected.
=> [Enhancement] Sanitize Medium blog content to only show first paragraph

docusaurus.config.js, openapi-specs/dns-security/dns-security.yaml
Addresses an incompatible OpenAPI plugin setting and a mismatch between operation tags and global tags.
Upcoming version of plugin will generate `info` doc which could lead to sidebar issues if the operation and global tags are not synched. Since `dns-security.yaml` is a single spec, `categoryLinkSource: "info"` is unnecessary. Instead, we can just render the "Introduction" doc.
See deploy preview.
=> DNS Security API fixes

src/css/custom.scss
Overrides details markers so that they better match the built-in caret markers used by Docusaurus.
Adds more consistent styling to details markers which is hopefully less distracting and a better UI/UX.
See deploy preview
Before:
After:
=> Override details markers to match Docusaurus caret

crumbs.json, src/theme/DocBreadcrumbs/index.js
Provides more control over breadcrumb links and generation while preserving existing functionality. All pages should act the same unless specifically changed in the crumbs.json file.
* Product breadcrumbs can now link to a product landing page by adding the key `make_link: true` to the crumbs.json
* Non-product breadcrumbs (eg. top level pages) that sometimes don't show up in the breadcrumbs can optionally show up now with `add_crumb: true` in the crumbs.json
Breadcrumbs that can link to a page don't currently. And breadcrumbs for top level pages that are not in the category are not in the breadcrumbs currently.
Tested locally
- [] I have added tests to cover my changes if appropriate.
- [] All new and existing tests passed.
=> Adds more control over breadcrumbs

openapi-specs/code/Policies.json
For the Code Sec Policies endpoints, added the deprecated: true tag to the spec file, and a note with a link to the replacement endpoints.
BCE-17644. Users should use CSPM Policies endpoints going forward. 
Tested the doc changes locally. 
Not a breaking change at the docs level. For API users it would be a breaking change at the product level when the Code Sec Policies endpoints are removed. 
=> Deprecated the Policies endpoints

products/terraform/docs/swfw/aws/vmseries/overview.mdx, products/terraform/docs/swfw/azure/vmseries/overview.mdx, products/terraform/docs/swfw/gcp/vmseries/overview.mdx
Include references to the intro for `Examples` in the SWFW pages for AWS, Azure and GCP
This was missed in a previous launch; the into page was created, but not referred to
Locally with yarn
=> docs: Include reference to Examples intro for SWFW pages

CODEOWNERS, products/contributing/advanced/auto-generated-docs.md
Adds codeowners and contributing guide for SWFW content linked from the [Orchestration Hub](https://pan.dev/swfw)
To conclude the build of the content system for SWFW content. The content sync system has been tested successfully and will used for future updates to the SWFW content for Terraform. This requires that the relevant team has permission to review PRs for their docs which are copied into pan.dev. Also a contributing guide has been added to make future contributors aware that they should not attempt to modify the relevant content directly in the pan.dev repo.
Test locally with yarn
=> Add codeowners and contributing guide for SWFW content

.github/workflows/deploy-preview.yml
Updates the deploy-preview workflow to allow `create-pr-on-fork-for-pan-dev[bot]` to continue without manual approval.
=> Whitelist create-pr-on-fork-for-pan-dev[bot]

src/components/CertExpireBanner/index.js, src/components/CertExpireBanner/styles.scss, src/pages/swfw.js, src/pages/swfw.scss
Adds a banner to the Orchestration Hub landing page with notification of the PAN-OS Root Cert Expiration advisory
Tested locally
=> chore(swfw): Add cert expire banner to Orchestration Hub

products/prisma-cloud/api/cspm/ratelimits.md
> [RLP-139832](https://redlock.atlassian.net/browse/RLP-139832)
Update Rate Limiting documentation page following the [API rate limit look ahead notice](https://docs.prismacloud.io/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure#api-rate-limits). 
- Additional updates may follow in upcoming releases as limits are officially introduced
=> RLP-139832 Rate Limits Documentation Update 

firebase.json
Removes CSP configuration from firebase config
Over time, our CSP has become increasingly difficult to manage, especially given inline scripts and changing sources/origins.
This has not been tested. The expectation is that removing the policy directives will disable it altogether.
=> Remove content security policy

docusaurus.config.js, package.json, yarn.lock
Switch from esbuild-loader to swc-loader transpiler. The overall build performance appears to be on par and there is evidence that Docusaurus may be adding experimental options to enable this natively via the docusaurus config.
=> Switch to swc-loader

docusaurus.config.js
Docusaurus option that allows docs with `.md` extension to be processed using `commonmark`, as opposed to MDX. 
Currently, upgrading to Docusaurus v3 is blocked by MDX parsing/syntax errors that exist in `.md` files, including `{`, `<<<`, indented code blocks and other cases. The hope is that this change will address the majority or all of the MDX parsing issues encountered when testing upgrading to v3. 
See #667 for more background.
Will test using the deploy preview
=> Enable processing md files as commonmark

src/components/SidebarMenu/index.js, src/css/custom.scss
Adds a custom sidebar menu component to allow contributors to implement a dropdown menu at any position in a sidebar.
Example: 
https://github.com/user-attachments/assets/42884ee1-41f7-4e3e-b300-57fd73421dc3
Example sidebars.js (note that the first argument/parameter is the dropdown label and the second is the array of menu items):
```
const sidebarMenu = require("../../src/components/SidebarMenu");
module.exports = {
expedition: [
{
type: "html",
defaultStyle: true,
value: sidebarMenu("Select Config Type", [
{ label: "This is an even longer test", baseUrl: "/" },
{ label: "This is a test", baseUrl: "/" },
{ label: "This is a medium length test", baseUrl: "/" },
]),
className: "sidebar__menu-button dropdown--hoverable dropdown--left", // see https://infima.dev/docs/components/dropdown for …
```
=> Add custom sidebar menu component

products/cross-platform/docs/service-status-api.mdx, products/sase/docs/service-status-api.mdx
Adds more details for consuming the Status Page APIs, on top of the original documentation which just pointed to URLs.
The first PR (#746) intentionally just listed the URLs of the APIs. This second part adds narrative on the API endpoints, what they provide, and potential values of key properties in the JSON response payloads.
Locally
=> More details for Status Page APIs

openapi-specs/cspm/AuditLogsMicroService.json
**RLP-151119**: Add Rate limit to descriptions on Audit Log Microservice endpoints
- _clean install and build_
- `yarn start:cloud`
- Documentation
=> Add rate limit description notice to AuditLogsMicroservice endpoints

openapi-specs/cspm/AssetMicroService.json, src/css/custom.scss, src/theme/Schema/index.tsx
Patched `Schema` component to work around malformed `discriminator` schemas in some CSPM APIs. Will continue working with CSPM team to cleanup/address OpenAPI specs and work on adding additional error handling to OpenAPI docs plugin.
=> Apply patch to schema component to workaround broken discriminators

openapi-specs/ai-runtime-security/scan/ScanService.yaml
Authentication
Local Dev server
- API Ref docs change
=> Update AIRS APIs for auth scheme

src/components/FloatingIsland/index.js, src/components/FloatingIsland/styles.css, src/theme/DocItem/Footer/index.tsx
Removes applause button
Retiring feature due to low adoption/value
see deploy preview
=> Remove applause button from doc footer and floating island

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-live.yml, .github/workflows/deploy-preview.yml
GitHub recommends pinning actions to a full length commit SHA, as this is currently the only method of using an action as an immutable release.
For more information refer to: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> Pin GitHub Actions

docusaurus.config.ts, yarn.lock
Updates links in nav/landing page to point to Cortex developer docs site (previously cortex.pan.dev).
=> Update Cortex docs link in mega-nav and landing page

src/components/CopyButton/index.js, src/components/CopyButton/styles.css
Disables pointer events for icon container to ensure click class is `copy-markdown-btn`.
=> Disable pointer events for copy icons

src/components/CopyButton/index.js, src/components/Tooltip/index.js
This PR consists of adding a missing `tabindex` attribute to the Copy for AI button.
Allow users to tab through the Copy for AI button 
Navigating to a docs page and ensuring that the Copy for AI button can be tabbed through.
https://github.com/user-attachments/assets/a580d727-df83-4d4d-80d6-cfb6ac57e308
=> [WebUI] Add missing tab index to Copy for AI button

package.json, scripts/feed2json.js, src/components/Medium/index.js, src/components/ProductLandingPage/Feeds/Feeds.js, yarn.lock
Ditches https://www.toptal.com/developers/feed2json/ for a custom node script that handles reading, parsing and converting Medium and Terraform RSS/XML feeds to JSON format.  
With this new approach, the feeds will be fetched using the `feed2json.js` script. The script will output JSON with empty items if a self-signed certificate error is encountered during the fetch.
> Note: I also wrapped the JSON imports in try/catch as an additional fall back
Over-reliance on services like toptal has caused issues in the past due to service outage, caching, etc.
Tested in local dev - see deploy preview to verify it works in prod.
=> Move to custom blog parser/converter

src/css/custom.scss
This PR addresses the following warning by replacing the use of `@import` (currently deprecated) with `@use` for importing tailwind styles.
```
[WARNING] {"message":"  ⚠ ModuleWarning: Deprecation Warning on line 14, column 8 of file:///Users/blinda/Desktop/projects/pan.dev/src/css/custom.scss:14:8:\n  │ Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.\n  │ \n  │ More info and automated migrator: https://sass-lang.com/d/import\n  │ \n  │ 14 | @import \"tailwindcss\";\n  │ \n  │ \n  │ src/css/custom.scss 15:9  root stylesheet\n  │  (from: /Users/blinda/Desktop/projects/pan.dev/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[10].oneOf[1].use[3])\n","moduleIdentifier":"/Users/blinda/Desktop/projects/pan.dev/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[ …
```
=> [WebUI] Update deprecated @import with @use for tailwindcss

src/css/custom.scss
The introduction of tailwindcss appears to have polluted `ul` list styles, effectively preventing uniform lists from rendering bullets, numbering, etc. This change attempts to revert to default `list-style` to allow for rendering list markers.
Will need to scrub styles to see what if anything else could be affected.
List markers make it easier to organize and read some content.
Tested locally in dev.
Before: 
After:
=> Revert default list-style

products/ai-runtime-security/api/pythonsdk.md, products/ai-runtime-security/api/pythonsdkasynciousage.md, products/ai-runtime-security/api/pythonsdkusage.md, products/ai-runtime-security/api/usecases.md, products/ai-runtime-security/sidebars.ts
* Add error handling and updated scan snippets
* Inline and Asyncio example updates
Help Developers with the use cases of PythonSDK API for code security.
Give sample code snippets for inline and asyncio examples.
Live Dev server
=> Pythonsdk update

src/theme/Root.js
Filters out ChunkLoadError exceptions from being forwarded to StackDriver
StackDriver error reporting is intended for finding broken pages, or pages that exit with an exception for any reason. ChunkLoadError occurs after a new site deploy, since browser cache needs to "catch up" to the new CDN chunks available, and can be safely ignored.
see deploy preview
=> filter out ChunkLoadError exceptions

package.json, src/components/ProductLandingPage/Feeds/Feeds.js
Removing Hashicorp blog feed from /terraform page. 
Hashicorp recently enabled Vercel's bot protection which is preventing us from fetching the feed in GitHub Actions. 
deploy preview
=> Decommission hashicorp blog feed
