PaloAltoNetworks/pan.dev

- static/_redirects
> add demisto redirect

- .gitignore
- firebase.json
- package.json
- src/components/Medium/index.js
- src/components/Medium/styles.module.css
* cleanup featured blogs
* add command to fetch recent blogs
> Fetch fresh blogs from Medium

- .github/workflows/codeql-analysis.yml
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
* migrate from `pull_request_target` to `workflow_run`
* move CodeQL back to separate workflow
* run CodeQL only for PRs
> refactor workflows

- docusaurus.config.js
Algolia recently updated and migrated our indexes to new AppIDs.
Changes point to new AppID and index to ensure we can search the most updated content.
Local dev instance. 
> Move to new Algolia AppID and index

- src/components/Medium/styles.module.css
- src/css/custom.css
* Adds light `box-shadow` to blog items (mostly visible in light mode)
* Override primary button background color (and remove border)
> Fix dark/light mode button and blog styles

- plugin-sitemap-coveo/src/createSitemap.cjs
> remove-osversion

- sase/docs/release-notes/changelog.md
- sase/docs/release-notes/release-notes.md
> Publish 5 16 2022

- docusaurus.config.js
- sase/api/iam/useraccounts.mdx
- sase/docs/release-notes/changelog.md
- sase/docs/release-notes/release-notes.md
- sase/sidebar.js
- static/sase/spec/iam/AccessPolicies.yaml
- static/sase/spec/iam/Permissions.yaml
- static/sase/spec/iam/Roles.yaml
- static/sase/spec/iam/ServiceAccounts.yaml
- static/sase/spec/iam/UserAccounts.yaml
> Publish 5 25

- docusaurus.config.js
- sase/api/insights/1.0/insights-api.md
- sase/api/insights/2.0/insights-api.md
- sase/docs/insights/getting_started-10.md
- sase/docs/insights/getting_started-20.md
- sase/docs/insights/insights.md
- sase/docs/release-notes/changelog.md
- static/sase/spec/tenancy/TenantServiceGroup.yaml
> Publish 7 5 2022

- cdss/threat-vault/docs/examples/threat-vault/antivirus-signature-hashes.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-atp-report-pcap.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-atp-report.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-release-notes.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-threat-signature-history.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-threat-signature-metadata-antivirus.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-threat-signature-metadata-ips.mdx
- cdss/threat-vault/docs/examples/threat-vault/get-threat-signature-metadata.mdx
- cdss/threat-vault/docs/examples/threat-vault/single-threat-id.mdx
- cdss/threat-vault/docs/examples/threat-vault/threat-id-batch-mode.mdx
> fix links to ref

- static/cloudngfw/aws/spec/api/AssociateRulestacks.yaml
- static/cloudngfw/aws/spec/api/ManageAPITokens.yaml
- static/cloudngfw/aws/spec/api/ManageCertificateObjects.yaml
- static/cloudngfw/aws/spec/api/ManageCommitConfiguration.yaml
- static/cloudngfw/aws/spec/api/ManageCustomURLCategories.yaml
- static/cloudngfw/aws/spec/api/ManageFQDNLists.yaml
- static/cloudngfw/aws/spec/api/ManageFileBlockingActions.yaml
- static/cloudngfw/aws/spec/api/ManageIntelligentFeeds.yaml
- static/cloudngfw/aws/spec/api/ManageLogProfiles.yaml
- static/cloudngfw/aws/spec/api/ManageNGFW.yaml
- static/cloudngfw/aws/spec/api/ManageNGFWTags.yaml
- static/cloudngfw/aws/spec/api/ManagePredefinedURLCategories.yaml
- static/cloudngfw/aws/spec/api/ManagePrefixLists.yaml
- static/cloudngfw/aws/spec/api/ManageRulestackTags.yaml
- static/cloudngfw/aws/spec/api/ManageRulestacks.yaml
- static/cloudngfw/aws/spec/api/ManageSecurityRules.yaml
- static/cloudngfw/aws/spec/api/ManageSubscription.yaml
- static/cloudngfw/aws/spec/api/UserOnboarding-LinkAccounts.yaml
- static/cloudngfw/aws/spec/api/UserOnboarding-MemberAccounts.yaml
> Publish 08 12 22

- sase/api/prisma-access-config/trafficsteering.mdx
- sase/docs/release-notes/changelog.md
- sase/docs/release-notes/release-notes.md
- static/sase/spec/prisma-access-config/Certificates.yaml
- static/sase/spec/prisma-access-config/Locations.yaml
- static/sase/spec/prisma-access-config/TrafficSteering.yaml
- static/sase/spec/prisma-access-config/sidebar_builder.js
> Publish 8 16 2022

- cdl/logforwarding/api/emailprofiles.mdx
- cdl/logforwarding/api/httpsprofiles.mdx
- cdl/logforwarding/api/logforwarding.md
- cdl/logforwarding/api/syslogprofiles.mdx
- cdl/logforwarding/docs/getstarted_lf.mdx
- cdl/logforwarding/docs/home.mdx
- cdl/logforwarding/docs/https_lf
- cdl/logforwarding/docs/https_lf.mdx
- cdl/logforwarding/docs/specifylogs_lf.mdx
- cdl/logforwarding/docs/syslog_lf
- cdl/logforwarding/docs/syslog_lf.mdx
- cdl/sidebar.js
- crumbs.json
- docusaurus.config.js
- static/cdl/logforwarding/spec/EmailProfiles.yaml
- static/cdl/logforwarding/spec/HTTPSProfiles.yaml
- static/cdl/logforwarding/spec/SyslogProfiles.yaml
- static/cdl/logforwarding/spec/sidebar_builder.js
> Publish 10 11 2022

- docusaurus.config.js
- sase/docs/home.mdx
- sase/docs/release-notes/changelog.md
> Added pointers to the log forwarding APIs from SASE

- sase/docs/access-tokens.mdx
> TSG_ID should be tsg_id

- docusaurus.config.js
- products/access/api/prisma-access-config/config-api.md
- products/access/docs/insights/getting_started-10.md
- products/access/docs/insights/getting_started-20.md
- products/cdl/docs/logforwarding/https_lf.mdx
- products/cdl/docs/logforwarding/specifylogs_lf.mdx
- products/cdl/docs/logforwarding/syslog_lf.mdx
- products/cdss/sidebars.js
- products/sase/docs/access-tokens.mdx
- products/sase/docs/mt-monitor/filters.md
- products/sase/docs/mt-monitor/mt-monitor.md
- products/sase/docs/release-notes/changelog.md
- products/sase/docs/release-notes/release-notes.md
- products/threat-vault/docs/examples/get-atp-report-pcap.mdx
- products/threat-vault/docs/examples/get-atp-report.mdx
- products/threat-vault/docs/examples/get-release-notes.mdx
- products/threat-vault/docs/examples/get-threat-signature-history.mdx
- products/threat-vault/docs/examples/get-threat-signature-metadata-antivirus.mdx
- products/threat-vault/docs/examples/get-threat-signature-metadata-ips.mdx
- products/threat-vault/docs/examples/get-threat-signature-metadata.mdx
- products/threat-vault/docs/response-fields/threat-vault-response-fields.mdx
> techdocs content and link fixes

- products/sdwan/api/legacy/home.md
> fixed slug for SDWAN legacy intro API topic

- firebase.json
> add redirects to site

- crumbs.json
- docusaurus.config.js
- package.json
- src/theme/DocBreadcrumbs/index.js
- src/theme/DocBreadcrumbs/styles.module.css
Updating Algolia search config to properly link out to external sites. 
Adding a selector to group by product within Algolia search
Add CDL, Terraform, and Ansible to Crumbs
Break up SASE Vertical products in Crumbs 
Add panos, terraform, ansible to the start:netsec command
> [DRAFT]Update Search & Add Product to Breadcrumbs

- .github/workflows/deploy-preview.yml
Updates the `Include netsec` products include list.
> Note: also cleans up new lines
> Update include netsec products

- README.md
- products/contributing/advanced/_category_.json
- products/contributing/advanced/partial-builds.md
Introduces guide on using `PRODUCTS_INCLUDE` to speed up development and production builds.
Help improve contributing experience.
Visit `/contributing` once the deploy preview is available.
> Note: I am using partial builds for this deploy preview: see the "contributing" label I added to this PR
> [Documentation] Partial builds and README updates

- docusaurus.config.js
Introduces HashiCorp Configuration Language  (HCL) syntax highlighting using prism.
> Add HCL syntax highlighting

- products/access/docs/insights/examples/pa-locations-dashboard/location-ep-status.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-gp-mobile-users-logins.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-mu-status.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-rn-bandwidth.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-rn-status.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-sc-bandwidth.md
- products/access/docs/insights/examples/pa-locations-dashboard/location-sc-status.md
- products/access/docs/insights/examples/pa-locations-dashboard/pa-locations-dashboard.md
> typo fixes

- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-live.yml
- .github/workflows/deploy-preview.yml
- package.json
Optimizes build pipelines to take full advantage of large github runners.
Speed up build times.
* Build strategy tested locally
* Actual workflows can't be tested until merged to master
> Optimize build pipeline

- products/ansible/docs/panos/guides/offline-content-software-upgrade.mdx
- products/ansible/docs/panos/guides/search-and-remove.mdx
- products/ansible/docs/panos/sidebars.js
- products/terraform/docs/panos/guides/policy-from-yaml.mdx
- products/terraform/sidebars.js
Three new guides for Ansible/Terraform
More guides is good
Tested locally with yarn
- New feature (non-breaking change which adds functionality) - new docs
> Three new guides for Ansible/Terraform

- openapi-specs/sase/subscription/Instance.yaml
- openapi-specs/sase/subscription/Licenses.yaml
- products/sase/api/subscription/subscription-api.md
- products/sase/docs/home.mdx
- products/sase/docs/release-notes/changelog.md
> Publish 12 5 2022

- src/components/Applause/index.js
- src/components/Applause/styles.css
- src/css/custom.scss
- src/theme/DocItem/Footer/index.tsx
> updated styling of claps

- src/theme/DocItem/Footer/index.tsx
- src/theme/DocItem/Footer/styles.module.css
Added mobile support for items within `EditMetaRow`.
https://user-images.githubusercontent.com/48506502/206046220-0d6a3a10-df1c-41d6-adea-c8a74097c137.mov
> [UI] Added mobile support for EditMetaRow

- openapi-specs/iot/api/public/bulkUpdateIPAMSubnet.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
> Update IoT Subnet API documentation

- openapi-specs/sase/mt-monitor/DataResources.yaml
- openapi-specs/sase/mt-monitor/InsightsResources.yaml
- openapi-specs/sase/mt-monitor/LicenseResources.yaml
- openapi-specs/sase/mt-monitor/TenantResources.yaml
- products/access/api/prisma-access-config/config-api.md
- products/sase/api/mt-monitor/msp-api.md
- products/sase/docs/mt-monitor/mt-monitor.md
> Publish 1 12 23

- docusaurus.config.js
- package.json
- src/theme/Root.js
- yarn.lock
Integrates with Error Reporting API to forward frontend errors for monitoring purposes.
Runtime errors can be difficult to detect outside of manually hunting for them.
Tested with staging site
> Implement frontend error reporting service

- package.json
- yarn.lock
Update yarn.lock with new registry
Also adds `cross-env` so that `yarn start:sase` and `yarn start:netsec` work on Windows.
> Update yarn.lock with new registry

- products/expedition/docs/creating_credentials.mdx
- products/expedition/docs/expedition_contact.md
- products/expedition/docs/expedition_workflow_bulkchange.md
- products/expedition/docs/expedition_workflow_filters.md
- products/expedition/docs/expedition_workflow_migration.md
- products/expedition/docs/expedition_workflow_removeunusedobject.md
- products/expedition/docs/expedition_workflow_searchrule.md
- products/expedition/docs/workflow.mdx
- products/expedition/sidebars.js
Modify Obtaining API Keys page to the correct syntax
API Syntax changed
Tested it in the local 
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- x[ ] All new and existing tests passed.
> Modify Obtaining API Keys page to the correct syntax.

- products/sdwan/docs/sdwan_gsg_sdk.md
> fix missing string quotes

- openapi-specs/sdwan/unified/Applications.yaml
- openapi-specs/sdwan/unified/BulkOperations.yaml
- openapi-specs/sdwan/unified/DNSServices.yaml
- openapi-specs/sdwan/unified/DeviceConfiguration.yaml
- openapi-specs/sdwan/unified/IPFIX.yaml
- openapi-specs/sdwan/unified/NATPolicy.yaml
- openapi-specs/sdwan/unified/PathPolicy.yaml
- openapi-specs/sdwan/unified/QOSPolicy.yaml
- openapi-specs/sdwan/unified/SecurityPolicy.yaml
- openapi-specs/sdwan/unified/Topology.yaml
> DOCS-2388 : SDWAN Unified changes

- src/constants/terraform/index.js
Update versions of Terraform elements
Update versions of Terraform elements
Locally with yarn
> Latest version numbers for Terraform elements

- .prettierignore
- package.json
- products/expedition/docs/expedition_apiInt.md
- products/expedition/docs/managing_jobs.mdx
Remove prettier from md and mdx files
> remove pretty from md due to formatting issues. Fix issues

- docusaurus.config.js
- src/components/Featured/index.js
- src/components/HompageHero/HomepageHero.js
- src/components/HompageHero/HomepageHero.scss
- src/pages/index.js
This PR consists of the following: 
- Reduced Hero padding 
- Removal of "Explore our Developer Docs" header
- Change of Product card ordering to:
1. Cloud Native Security 
2. Security Operations 
3. Network Security 
4. Secure Access Service Edge
Changes were made to increase visibility across all four Product categories on initial desktop load.
> [UI] Landing Page Updates

- CODEOWNERS
Updates to CODEOWNERS
- Update path for SASE
- Add CODEOWNERS for PAN-OS/IaC/PaC
N/A
N/A
N/A
> Updates to CODEOWNERS

- openapi-specs/sdwan/unified/Applications.yaml
- openapi-specs/sdwan/unified/NATPolicy.yaml
- openapi-specs/sdwan/unified/PathPolicy.yaml
- openapi-specs/sdwan/unified/PathPolicyOriginal.yaml
- openapi-specs/sdwan/unified/QOSPolicy.yaml
- openapi-specs/sdwan/unified/SecurityPolicy.yaml
- openapi-specs/sdwan/unified/Service&DCGroups.yaml
- openapi-specs/sdwan/unified/SiteConfiguration.yaml
- openapi-specs/sdwan/unified/SoftwareManagement.yaml
- openapi-specs/sdwan/unified/SystemAdministration.yaml
> updates for SDWAN unified descriptions

- products/prisma-cloud/docs/cspm/manage-saved-search.md
> fixed broken link

- products/prisma-cloud/docs/cspm/aws-cloud-account-onboarding.md
- products/prisma-cloud/docs/cspm/aws-cloud-organization-onboarding.md
> AWS Onboarding api workflow update descriptions

- src/constants/terraform/index.js
Preview: https://pan-dev-f1b58--pr317-s4ka3n0h.web.app/terraform/
- Updated Terraform provider cards with the latest version
- [Cloud NGFW](https://registry.terraform.io/providers/PaloAltoNetworks/cloudngfwaws/latest) - `v2.0.1`
- [Prisma Cloud](https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest) - `v1.3.2`
> Update Terraform Provider cards to latest version

- openapi-specs/sdwan/unified/ADEM.yaml
- openapi-specs/sdwan/unified/Applications.yaml
- openapi-specs/sdwan/unified/Cellular.yaml
- openapi-specs/sdwan/unified/DNSServices.yaml
- openapi-specs/sdwan/unified/DeviceConfiguration.yaml
- openapi-specs/sdwan/unified/EventPolicy.yaml
- openapi-specs/sdwan/unified/IPFIX.yaml
- openapi-specs/sdwan/unified/Multicast.yaml
- openapi-specs/sdwan/unified/NATPolicy.yaml
- openapi-specs/sdwan/unified/NetworkConstructs.yaml
- openapi-specs/sdwan/unified/PathPolicy.yaml
- openapi-specs/sdwan/unified/PathPolicyOriginal.yaml
- openapi-specs/sdwan/unified/PrismaAccessConfigs.yaml
- openapi-specs/sdwan/unified/QOSPolicy.yaml
- openapi-specs/sdwan/unified/Routing.yaml
- openapi-specs/sdwan/unified/SecurityPolicy.yaml
- openapi-specs/sdwan/unified/Service&DCGroups.yaml
- openapi-specs/sdwan/unified/SiteConfiguration.yaml
- openapi-specs/sdwan/unified/SoftwareManagement.yaml
- openapi-specs/sdwan/unified/SystemAdministration.yaml
- openapi-specs/sdwan/unified/Topology.yaml
- products/sase/docs/api-call.mdx
> editorial updates to unified sdwan, x-panw-region in sase get started

- openapi-specs/cspm/AdoptionAdvisor.json
- openapi-specs/cspm/CloudAccounts.json
- openapi-specs/cspm/DataSecurityOnboardingMicroService.json
- openapi-specs/cspm/DataSecuritySettings.json
> deprecated endpoints

- crumbs.json
- docusaurus.config.js
- openapi-specs/access/prisma-access-config/ApplicationOverrideRules.yaml
- openapi-specs/access/prisma-access-config/AuthenticationRules.yaml
- openapi-specs/access/prisma-access-config/DecryptionRules.yaml
- openapi-specs/access/prisma-access-config/IKEGateways.yaml
- openapi-specs/access/prisma-access-config/IPSecTunnels.yaml
- openapi-specs/access/prisma-access-config/MobileAgent.yaml
- openapi-specs/access/prisma-access-config/QoSPolicyRules.yaml
- openapi-specs/access/prisma-access-config/SecurityRules.yaml
- openapi-specs/access/prisma-access-config/TrafficSteeringRules.yaml
- openapi-specs/access/ztna/paloaltonetworks-ztna-connector.yaml
- products/access/sidebars.js
- products/sase/docs/api-call.mdx
- products/sase/docs/home.mdx
- products/sase/docs/mt-monitor/mt-monitor.md
- products/sase/docs/release-notes/changelog.md
- products/sase/docs/release-notes/release-notes.md
- products/sdwan/api/home.md
- yarn.lock
> Publish 4 27 2023

- docusaurus.config.js
- openapi-specs/access/ztna/paloaltonetworks-ztna-connector.yaml
- openapi-specs/sase/iam/AccessPolicies.yaml
- openapi-specs/sase/iam/CustomRoles.yaml
- openapi-specs/sase/iam/PermissionSets.yaml
- openapi-specs/sase/iam/Permissions.yaml
- openapi-specs/sase/iam/Roles.yaml
- openapi-specs/sase/iam/ServiceAccounts.yaml
- openapi-specs/sase/iam/UserAccounts.yaml
- products/sase/docs/release-notes/changelog.md
> Publish 5 16 2023

- openapi-specs/cspm/Alerts.json
- products/prisma-cloud/api/cspm/api-integration-config.md
> RLP-96961 - Webhook changes & PCSUP-16044- Alert changes

- openapi-specs/access/prisma-access-config/RemoteNetworks.yaml
> corrected the definition of ecmp_tunnels

- openapi-specs/compute/openapi_30_01_153.json
- openapi-specs/cwpp/openapi_30_01_152.json
Updated OpenAPI spec for the hotfix in Maxwell Update 1.
Updated OpenAPI spec for the hotfix in Maxwell Update 1.
Tested on a local machine.
> Maxwell Update 1: Hotfix build

- crumbs.json
> prisma cloud updated tags for coveo search

- crumbs.json
> updated the osversion

- crumbs.json
> removed prisma and prisma cloud

- openapi-specs/iot/api/public/addingTag.yaml
- openapi-specs/iot/api/public/removingTag.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
- openapi-specs/iot/iot.yaml
> Adding tag public api

- openapi-specs/cspm/CloudAccounts.json
> Checking in Fix for Add Azure Account 404 Error

- src/constants/swfw/index.js
- src/pages/swfw.scss
Added enhancements including additions to light and dark mode, card responsiveness and text changes on swfw page
Change requested by team to enhance the visuals and text of the webpage.
Manual visual testing
> light/dark mode edits, card enhancements, and text edits on swfw page

- openapi-specs/access/prisma-access-config/MobileAgent.yaml
- openapi-specs/access/prisma-access-config/RemoteNetworks.yaml
> Publish 6 24 2023

- .github/workflows/deploy-preview.yml
- package.json
This PR consists the following: 
1. Update `start:cloud` script to only reflect the needed cloud doc product directories
2. Include the cloud step into the Deploy Preview workflow
Build issues related to https://github.com/PaloAltoNetworks/pan.dev/pull/434
> Update start:cloud script and add cloud step to deploy preview workflow

- products/splunk/docs/troubleshoot.md
Fixed link with paths to the root.
Links were broken had to change them to relative path.
Tested locally
-
> docs(splunk-docs): Update broken links in troubleshooting guide

- products/ansible/docs/panos/guides/eda-decryption-remediation.mdx
- products/ansible/landing.mdx
- products/ansible/sidebars.js
New documentation content for Ansible EDA
EDA was recently added to the PAN-OS Ansible Collection
Locally with yarn
- New docs
> docs: New Ansible EDA doc

- openapi-specs/cspm/README.md
- openapi-specs/cspm/print_opertaionIds_tag_pairs.sh
> added more content to readme

- products/panos/docs/panos-upgrade-assurance.mdx
- products/panos/docs/panos-upgrade-assurance/api/check_firewall.md
- products/panos/docs/panos-upgrade-assurance/api/exceptions.md
- products/panos/docs/panos-upgrade-assurance/api/firewall_proxy.md
- products/panos/docs/panos-upgrade-assurance/configuration_details.mdx
- products/panos/docs/panos-upgrade-assurance/dialect.mdx
- products/panos/docs/panos-upgrade-assurance/usage_examples.mdx
A PR made for changes introduced into documentation on v0.2.0 release.
New feature (non-breaking change which adds functionality)
> [PAN-OS Upgrade Assurance] documentation update for release: v0.2.0

- openapi-specs/cspm/Alerts.json
- openapi-specs/cspm/ResourceExplorer.json
- openapi-specs/cspm/SearchMicroService.json
- openapi-specs/cspm/consolidated_spec/all_endpoints.csv
> 23.9.2 Updates

- products/access/docs/adem/examples/application-performance/mu-experience-score-for-an-app.md
- products/access/docs/adem/examples/application-performance/network-performance-metrics-for-an-application.md
- products/access/docs/adem/examples/application-performance/timeseries-data-of-application-performance-for-all-applications.md
- products/access/docs/adem/examples/application-test/distribution-for-an-app-test-per-segment.md
- products/access/docs/adem/examples/application-test/distribution-for-an-application-test.md
- products/access/docs/adem/examples/application-test/global-distribution-of-app-score-for-an-app-test.md
- products/access/docs/adem/examples/application-test/network-performance-metrics.md
- products/access/docs/adem/examples/application-test/timeseries-data-for-an-app-test.md
- products/access/docs/adem/examples/application-test/timeseries-of-app-performance-metrics-for-an-app-test.md
- products/access/docs/adem/examples/application-test/top-20-applications-lowest-to-highest-experience-score.md
- products/access/docs/adem/examples/mobile-users/distribution-of-mu-agent-scores-by-endpoint-across-all-tests.md
- products/access/docs/adem/examples/mobile-users/distribution-of-mu-application-score.md
- products/access/docs/adem/examples/mobile-users/experience-score-for-top-monitored-mu-devices.md
- products/access/docs/adem/examples/mobile-users/fetch-all-mu-adem-agents-logged-in-for-last-30-days.md
- products/access/docs/adem/examples/mobile-users/global-distribution-of-application-experience-scores-for-mu-devices.md
- products/access/docs/adem/examples/mobile-users/mu-agent-score-aggregated-across-all-endpoints.md
- products/access/docs/adem/examples/mobile-users/timeseries-of-mu-agent-scores.md
- products/access/docs/adem/examples/remote-networks/adem-apis-for-rns.md
- products/access/docs/adem/examples/zoom-data/fetch-zoom-meeting-data-for-a-user.md
- products/sase/docs/release-notes/changelog.md
- products/sase/docs/release-notes/release-notes.md
> Publish 9 29 2023

- openapi-specs/cspm/PermissionGroupsMicroService.json
- openapi-specs/cspm/adjustSpecFilesForPanDev.sh
- openapi-specs/cspm/src/filter.sh
Modified the script to modify the tag description only if the info description is present.
> 23.10.1 - Adding script change and minor edits in SSO category description

- docusaurus.config.js
Update CloudNGFW Terraform link in menu
Still using placeholder link
With preview site on Firebase
N/A
> Update CloudNGFW Terraform menu link

- src/components/Medium/index.js
- src/components/ProductLandingPage/Feeds/Feeds.js
- src/components/ProductLandingPage/Feeds/Feeds.scss
This PR addresses the following build error introduced in https://github.com/PaloAltoNetworks/pan.dev/pull/571
```
Error:  Docusaurus server-side rendering could not render static page with path /terraform/.
[success] [webpackbar] Server: Compiled with some errors in 25.50m
ReferenceError: feed is not defined
Error:  Unable to build website for locale en.
Error:  Error: Failed to compile with errors.
```
> [Bug Fix] Fix build error for Terraform page blogs

- products/panos/docs/panos-upgrade-assurance.mdx
- products/panos/docs/panos-upgrade-assurance/api/check_firewall.md
- products/panos/docs/panos-upgrade-assurance/api/firewall_proxy.md
- products/panos/docs/panos-upgrade-assurance/api/utils.md
- products/panos/docs/panos-upgrade-assurance/configuration_details.mdx
A PR made for changes introduced into documentation on v0.3.1 release.
New feature (non-breaking change which adds functionality)
> [PAN-OS Upgrade Assurance] documentation update for release: v0.3.1

- docusaurus.config.js
> Add cors proxy for dlp

- docusaurus.config.js
- openapi-specs/sase/mt-notifications/Multi-Tenant-Notifications.yaml
- products/access/docs/prisma-access-config/prisma-access-config.md
- products/sase/api/mt-notifications/notifications-api.md
- products/sase/docs/home.mdx
- products/sase/docs/mt-monitor/mt-monitor.md
- products/sase/docs/release-notes/changelog.md
- products/sase/sidebars.js
> Publish 4 15 2024

- openapi-specs/dlp/DLPAPI.yaml
> Dlp edits 4 22

- openapi-specs/iot/api/public/xsoarACLSyncStatus.yaml
- openapi-specs/iot/api/public/xsoarIntegrations.yaml
- openapi-specs/iot/api/public/xsoarVulnReportUpload.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
- openapi-specs/iot/iot.yaml
> 24.5.2 CSPM APIs

- openapi-specs/iot/api/public/heartbeat.yaml
- openapi-specs/iot/api/public/purgeRules.yaml
- openapi-specs/iot/api/public/scannerDetails.yaml
- openapi-specs/iot/api/public/thirdPartyScan.yaml
- openapi-specs/iot/api/public/updateSecurityRule.yaml
- openapi-specs/iot/api/public/xsoarStatus.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
- openapi-specs/iot/iot.yaml
add documents for IoT public apis
/pub/v4.0/network/securityRules
/pub/v4.0/network/purgeRules
/pub/v4.0/thirdPartyScan
/pub/v4.0/xsoar/status
/pub/v4.0/xsoar/device/scanDetails
/pub/v4.0/xsoar/heartbeat
Requested by QA team
test on local build
- [x ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes if appropriate.
- [ x] All new and existing tests passed.
> add doc for public apis

- docusaurus.config.js
> Test Send API request

- openapi-specs/cloudngfw/aws/ManageNGFW.yaml
Add the missing `LinkId` request parameter
Discussion and request in the Slack channel #help-cloud-ngfw.
This parameter is also included in the AWS TF
- API Refs doc change
> Add linkID in the request parameter

- docusaurus.config.js
> Disable Send API Request Button

- openapi-specs/dlp/DLPAPI.yaml
> Dlp updates 7 17

- products/expedition/docs/expedition.md
- products/expedition/docs/expedition_apiInt.md
- products/expedition/docs/expedition_contact.md
- products/expedition/docs/expedition_export.md
- products/expedition/docs/expedition_qs.md
- products/expedition/docs/expedition_workflow_bulkchange.md
- products/expedition/docs/expedition_workflow_filters.md
- products/expedition/docs/expedition_workflow_migration.md
- products/expedition/docs/expedition_workflow_removeunusedobject.md
- products/expedition/docs/expedition_workflow_searchrule.md
- products/expedition/docs/workflow.mdx
Updating contents to reflect EOS , fix export configuring for sonicwall.
Updating contents due to EOS of the product
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.
> Updating contents to reflect EOS

- products/panos/docs/panos-upgrade-assurance/api/check_firewall.md
- products/panos/docs/panos-upgrade-assurance/api/firewall_proxy.md
- products/panos/docs/panos-upgrade-assurance/api/snapshot_compare.md
- products/panos/docs/panos-upgrade-assurance/api/utils.md
- products/panos/docs/panos-upgrade-assurance/configuration_details.mdx
- products/panos/docs/panos-upgrade-assurance/dialect.mdx
- products/panos/docs/panos-upgrade-assurance/overview.mdx
- products/panos/docs/panos-upgrade-assurance/usage_examples.mdx
A PR made for changes introduced into documentation on v1.0.0 release.
New feature (non-breaking change which adds functionality)
> [PAN-OS Upgrade Assurance] documentation update for release: v1.0.0

- products/splunk/docs/adaptive-response.md
- products/splunk/docs/aperture.md
- products/splunk/docs/autofocus-and-minemeld.md
- products/splunk/docs/commands.md
- products/splunk/docs/cortex-hec.md
- products/splunk/docs/cortex-xdr.md
- products/splunk/docs/dashboards.md
- products/splunk/docs/enterprise-security.md
- products/splunk/docs/external-search.md
- products/splunk/docs/faq.md
- products/splunk/docs/firewalls-panorama.md
- products/splunk/docs/getting-data-in.md
- products/splunk/docs/health-checks.md
- products/splunk/docs/installation.md
- products/splunk/docs/intro.md
- products/splunk/docs/iot-security.md
- products/splunk/docs/log-correlation.md
- products/splunk/docs/lookups.md
- products/splunk/docs/release-notes.md
- products/splunk/docs/support.md
- products/splunk/docs/threat-intelligence.md
- products/splunk/docs/trial-demo.md
- products/splunk/docs/troubleshoot.md
- products/splunk/docs/tune-or-reduce-firewall-logs.md
- products/splunk/docs/universal-forwarder.md
- products/splunk/docs/userid.md
Messaging added to notify customers of app and add-on is deprecated.
> docs(splunk-docs): Add deprecated app notice.

- openapi-specs/ai-runtime-security/scan/ScanService.yaml
- products/ai-runtime-security/api/airuntimesecurityapi.md
- products/ai-runtime-security/api/usecases.md
AI Runtime Security: API Intercept URL updates
- Documentation change
> AIRS APIs updates

- products/access/api/insights/2.0/insights-api.md
- products/access/docs/insights/getting_started-20.md
- products/access/docs/insights/insights.md
- products/access/sidebars.js
> removed 2.0 deprecation note. added 2.0 sidebar back in

- openapi-specs/cspm/IAMV2MicroService.json
- openapi-specs/cspm/UVEDashboardMicroService.json
> CSPM Doc updates part1

- src/pages/strata-cloud-manager/index.js
- src/pages/strata-cloud-manager/scm.scss
My feable attempt to spruce up the SCM landing page hero.
Temporary until our UX team designs a more exciting solution.
see deploy preview
> Use SCM demo video as hero background

- src/pages/strata-cloud-manager/index.js
- src/pages/strata-cloud-manager/scm.scss
Slight variation on layout that extends video below cards section
> SCM Hero revised

- products/sase/docs/home.mdx
- products/sase/docs/release-notes/changelog.md
- products/scm/docs/release-notes/changelog.md
- src/pages/strata-cloud-manager/index.js
> Docs 7072 adding SSPM to SCM

- docusaurus.config.ts
- products/sase/docs/home.mdx
- products/sase/docs/release-notes/changelog.md
> DOCS-6603 Updated the links

- openapi-specs/iot/api/public/deleteCustomAttribute.yaml
- openapi-specs/iot/api/public/updateCustomAttribute.yaml
> BAN-20938_change_description

- openapi-specs/email-dlp/EmailDLPAPI.yaml
- products/email-dlp/api/email-dlp-overview.md
> email dlp updates for february

- openapi-specs/ai-runtime-security/scan/ScanService.yaml
- products/ai-runtime-security/api/usecases.md
Update the use cases to indicate the optional fields and update the input/output snippets.
Local Dev environment
> Update the use case to indicate optional field

- .github/workflows/deploy-preview.yml
Similar to #877, two more instances where only codeql is running on a different runner, so switching to `ubuntu-latest`
Use a different runner
> Run codeql on ubuntu-latest

- openapi-specs/ai-runtime-security/scan/ScanService.yaml
Update the async example with 2 request IDs and scan IDs.
Gives additional context on the result response of an async request.
Local Dev serverr
> Update async example

- openapi-specs/threat-vault/ThreatPrevention.yaml
- products/threat-vault/docs/examples/get-cve-coverage-information.mdx
> Update for CVE coverage - typos

- openapi-specs/ai-runtime-security/scan/ScanService.yaml
AIRS Scan API has new detections, updating the schema.
Update API schema for the user to scan new detections
Local dev server
> Update API Schema for new Detections

- products/ai-runtime-security/api/airuntimesecurityapi.md
- products/ai-runtime-security/api/usecases.md
Update API region support for EU only
Update API region support for EU only
Local dev server
> Update API region support for EU only

- openapi-specs/ai-runtime-security/scan/ScanService.yaml
- products/ai-runtime-security/api/airuntimesecurityapi.md
- products/ai-runtime-security/api/pythonsdk.md
- products/ai-runtime-security/api/pythonsdkusage.md
- products/ai-runtime-security/api/usecases.md
- products/ai-runtime-security/sidebars.ts
Add API support in EU region
Add API support in EU region
Local dev server
> Add EU API support

- openapi-specs/sase/sspm/SSPM.yaml
- products/sase/api/sspm/sspm-api-workflow.md
> Docs 7964 updated schema for app setting (SSPM)

- src/components/UseCasesTabs.js
- src/pages/airs/index.js
- src/pages/airs/styles.module.css
- src/pages/index.js
- src/pages/styles.module.css
> Polish AIRS Landing Page

- src/components/UseCasesTabs.jsx
Minor fix to use cases component to prevent shifting while selecting tabs
> Polish UseCasesTabs layout and styles

- products/scm/docs/getstarted.md
> updated curl example per eng

- openapi-specs/iot/api/public/createNetworkSegment.yaml
- openapi-specs/iot/api/public/createSite.yaml
- openapi-specs/iot/api/public/createSubnet.yaml
- openapi-specs/iot/api/public/deleteNetworkSegment.yaml
- openapi-specs/iot/api/public/deleteSite.yaml
- openapi-specs/iot/api/public/deleteSubnet.yaml
- openapi-specs/iot/api/public/getNetworkSegment.yaml
- openapi-specs/iot/api/public/getSite.yaml
- openapi-specs/iot/api/public/getSubnet.yaml
- openapi-specs/iot/api/public/revertSubnet.yaml
- openapi-specs/iot/api/public/transferSubnet.yaml
- openapi-specs/iot/api/public/updateNetworkSegment.yaml
- openapi-specs/iot/api/public/updateSite.yaml
- openapi-specs/iot/api/public/updateSubnet.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
- openapi-specs/iot/iot.yaml
> BAN-22100: Adding Public API Documentation for new IOT Public APIs - CRUD APIs for Subnets, Network Segments, and Sites Tables

- openapi-specs/iot/components/securitySchemes.yaml
- openapi-specs/iot/iot.yaml
- products/iot/api/iot-public-api-headers.md
- products/iot/api/iot-public-api-new.md
> BAN-21692 adding new public api flow

- products/expedition/docs/expedition_export.md
Remove Sonicwall Instructions per GCS
Remove Sonicwall Section
Requested by GCS
Testing
- [x ] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.
> Update expedition_export.md to remove sonicwall section

- openapi-specs/access/adem/paloaltonetworks-autonomous-dem.yaml
> Docs 8335 ADEM link update

- products/prisma-airs/api/airuntimesecurity/airuntimesecurityapi.md
New API endpiont added IN:https://service-in.api.aisecurity.paloaltonetworks.com/
Enhance AI Security with India Region Support
Local dev server
> Enhance AI Security with India Region Support

- openapi-specs/iot/api/public/deviceSearch.yaml
- openapi-specs/iot/components/examples.yaml
- openapi-specs/iot/components/schemas.yaml
- openapi-specs/iot/iot.yaml
- products/iot/api/iot-public-api-new.md
> BAN-23831 adding public api doc

- openapi-specs/dspm/dspm.json
> dspm july update
